name: build32

on:
  workflow_dispatch:

env:
  PACMAN_REPOSITORY_NAME: build32
  PACMAN_REPOSITORY_URL: https://github.com/jeremyd2019/msys2-build32/releases/download/repo

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: msys2
        uses: jeremyd2019/setup-msys2@v2_32
        with:
          msystem: MSYS
          install: p7zip tar
          update: true
          bitness: 32

      - name: Update
        continue-on-error: true
        run: |
          grep -qF "[${PACMAN_REPOSITORY_NAME}]" /etc/pacman.conf || sed -i "/\[msys\]/i [${PACMAN_REPOSITORY_NAME}]\nServer = ${PACMAN_REPOSITORY_URL}\nSigLevel = Optional\n" /etc/pacman.conf
          pacman --noconfirm --noprogressbar --sync --refresh --refresh --sysupgrade --sysupgrade

      - name: Kill
        shell: cmd
        run: |
          "%windir%\SysWOW64\WindowsPowerShell\v1.0\PowerShell.exe" -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { $_.Modules.ModuleName -contains 'msys-2.0.dll' } | Stop-Process -Force"

      - name: Update again
        run: |
          grep -qF "[${PACMAN_REPOSITORY_NAME}]" /etc/pacman.conf || sed -i "/\[msys\]/i [${PACMAN_REPOSITORY_NAME}]\nServer = ${PACMAN_REPOSITORY_URL}\nSigLevel = Optional\n" /etc/pacman.conf
          pacman --noconfirm --noprogressbar --sync --refresh --refresh --sysupgrade --sysupgrade

      - name: Kill and rebase
        shell: cmd
        run: |
          "%windir%\SysWOW64\WindowsPowerShell\v1.0\PowerShell.exe" -NoProfile -ExecutionPolicy Bypass -Command "Get-Process | Where-Object { $_.Modules.ModuleName -contains 'msys-2.0.dll' } | Stop-Process -Force"
          del "${{ steps.msys2.outputs.msysRootDir }}\etc\rebase.db.*"
          call "${{ steps.msys2.outputs.msysRootDir }}\autorebase.bat"

      - name: Build
        run: |
          sed -i 's/^IgnorePkg\s/#&/' /etc/pacman.conf
          bash -x make-msys2-installer
          sha256sum.exe msys2-* | tee msys2-checksums.txt
          mkdir artifacts
          mv msys2-* artifacts
          cp /tmp/installer-*.log artifacts

      - uses: actions/upload-artifact@v2
        with:
          name: output
          path: artifacts/
