name: build32

on:
  workflow_dispatch:

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: jeremyd2019/setup-msys2@v2_build32
        with:
          msystem: MINGW32
          install: tar mingw-w64-x86_64-7zip mingw-w64-i686-xz mingw-w64-x86_64-zstd
          update: true
          bitness: 32

      - name: Build
        run: |
          bash -x make-msys2-installer
          sha256sum.exe msys2-* | tee msys2-checksums.txt
          mkdir artifacts
          mv msys2-* artifacts

      - uses: actions/upload-artifact@v4
        with:
          name: output
          path: artifacts/
