name: build32

on:
  workflow_dispatch:

jobs:
  build32:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: jeremyd2019/setup-msys2@v2_build32
        with:
          msystem: MSYS
          install: p7zip tar mingw-w64-i686-qt-installer-framework
          update: true
          bitness: 32

      - name: Build
        run: |
          bash -x make-msys2-installer
          sha256sum.exe msys2-* | tee msys2-checksums.txt
          mkdir artifacts
          mv msys2-* artifacts
          cp /tmp/installer-*.log artifacts

      - uses: actions/upload-artifact@v3
        with:
          name: output
          path: artifacts/
